// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/themes/theme-arctic.tsx": () => import("../components/mockups/themes/theme-arctic.tsx"),
  "./components/mockups/themes/theme-clover-green.tsx": () => import("../components/mockups/themes/theme-clover-green.tsx"),
  "./components/mockups/themes/theme-default.tsx": () => import("../components/mockups/themes/theme-default.tsx"),
  "./components/mockups/themes/theme-ember.tsx": () => import("../components/mockups/themes/theme-ember.tsx"),
  "./components/mockups/themes/theme-forest.tsx": () => import("../components/mockups/themes/theme-forest.tsx"),
  "./components/mockups/themes/theme-midnight-navy.tsx": () => import("../components/mockups/themes/theme-midnight-navy.tsx"),
  "./components/mockups/themes/theme-rose-gold.tsx": () => import("../components/mockups/themes/theme-rose-gold.tsx"),
  "./components/mockups/themes/theme-slate.tsx": () => import("../components/mockups/themes/theme-slate.tsx"),
  "./components/mockups/themes/theme-square-clean.tsx": () => import("../components/mockups/themes/theme-square-clean.tsx"),
  "./components/mockups/themes/theme-toast-dark.tsx": () => import("../components/mockups/themes/theme-toast-dark.tsx")
};
